name: Markdown lint
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: gem install mdl
      # lint ignoring the line length lint
      - run: mdl -r ~MD013,~MD026 README.md
      - run: mdl -r ~MD013,~MD026 docs/*
